### PR TITLE
Make it installable from appstore

### PR DESCRIPTION
**Pull request by enoch85**
Avoid: "App can't be installed because the version in info.xml/version is not the same as the version reported from the app store"

### CODE REVIEW

**Comment by skjnldsv** [comment]
Didn't saw that, good call.

**Comment by enoch85** [comment]
Just tested 1.8 with oC 0 and it works. Could you please release 1.8.1 wo that this commit is in? Thank you! @skjnldsv

**Comment by enoch85** [comment]
And ofc, change to 1.8.1 before you release it. :)

**Comment by skjnldsv** [comment]
I'm working on it right now! I will release when I'm done coding the new calendar sync.

**Comment by skjnldsv** [comment]
It wasn't because of the info.xml.
It was the apps.owncloud.com config that wasn't right. I had to change the releases order and defined correct versions :p

**Comment by enoch85** [comment]
It's downloading fine now anyway. :)

**Pull request merged**
